WEEK 9/Day 4/school_proj/account/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('signup/',views.UserSignUp.as_view(),name="signup"),
]

WEEK 9/Day 4/school_proj/school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
    path('', include('students.urls'))
]

WEEK 9/Day 4/school_proj/students/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),

    path('subjects/', views.SubjectList.as_view(), name='subject-list'),
    path('subject/<int:pk>', views.SubjectDetails.as_view(), name='subject-details'),
    path('subjects/add', views.AddSubject.as_view(), name='subject-add'),

    path('students/', views.students_list, name='students'),
    path('students/add', views.add_student, name='students-add'),
    path('students/<int:id>', views.student_details, name='students-details'),

    path('search/', views.search, name='search'),


]

WEEK 9/Day 4/school_proj/account/models.py
from django.db import models

# Create your models here.

WEEK 9/Day 4/school_proj/students/models.py
from django.db import models
from django.contrib.auth.models import User

class Subject(models.Model):
    name = models.CharField(max_length=30)
    textbook = models.CharField(max_length=30)
    class_room = models.IntegerField()
    
    def __str__(self):
        return self.name


class Profile(models.Model):
    age = models.IntegerField()
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.user}"


class Student(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def sayHi(self):
        return f"Hi, my name is {self.first_name}, and I'm a {self.__class__.__name__.lower()}"



class Pet(models.Model):
    name = models.CharField(max_length=30)
    breed = models.CharField(max_length=30)
    owner = models.ForeignKey(Student, on_delete=models.CASCADE)  # Many to One

    def __str__(self):
        return f"{self.name}"

WEEK 9/Day 4/school_proj/account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    age = forms.IntegerField()

    class Meta:
        model = User
        fields = ["username", "first_name", "password1", "password2", "age"]

WEEK 9/Day 4/school_proj/students/forms.py
from django import forms
from .models import Subject


class SubjectForm(forms.ModelForm):
      class Meta:
            model = Subject
            fields = '__all__'
































# def validate_major(major):
#     # check if they are numbers in the name
#     if major != "Computer Programming":
#         print("Invalid Major")  
#         raise forms.ValidationError(f'This is a bootcamp. Your major must be Computer Programming')

class AddStudentForm(forms.Form):

      def sayHi(self):
            print("HI, I'm a studentForm for adding new students.")

      # def __init__(self, *args, **kwargs):
      #       super(AddStudentForm, self).__init__(*args, **kwargs)
      #       for item in self.visible_fields():
      #             item.field.widget.attrs['class'] = 'form-control'

      first_name = forms.CharField(
            required=True,
            label="Given Name", 
            help_text='This is the name your Momma gave you', 
            error_messages={'required': 'We need to know how to call'}
      )

      last_name = forms.CharField(
            required = True,
            widget = forms.TextInput(
                  attrs={
                        'placeholder': 'Write your name here',
                        'class': 'form-control'
                  }
            )
      )

      major = forms.CharField(
            required=False,
            # validators = [validate_major]
      )

      minor = forms.CharField(required=False, widget = forms.TextInput(attrs={'class': 'form-control'}))

      picture = forms.URLField(required=False,label="Pic URL", widget = forms.TextInput(attrs={'class': 'form-control'}))

WEEK 9/Day 4/school_proj/account/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import CreateView
from .forms import SignupForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from students.models import Profile

class UserSignUp(CreateView):
    template_name = "registration/signup.html"
    model = User
    form_class = SignupForm
    success_url = 'home'
    failed_message = "The User couldn't be added"


    def form_valid(self, form):
        super().form_valid(form)   

        user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
        
        Profile.objects.create(user=user, age=form.cleaned_data['age'])

        if user:
            login(self.request, user)
            
        return redirect(reverse(self.get_success_url()))

WEEK 9/Day 4/school_proj/students/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.http import HttpResponse
from .models import *
from .forms import AddStudentForm, SubjectForm
from django.urls import reverse_lazy

from django.contrib.auth.decorators import login_required

from django.contrib.auth.mixins import LoginRequiredMixin

from django.views import View
from django.views.generic import ListView, DetailView, CreateView, YearArchiveView

from time import sleep

from random import choice
import json

# Create your views here.


class SubjectList(LoginRequiredMixin, ListView):
    model = Subject
    template_name = 'subjects/subject_list.html'


class SubjectDetails(DetailView):
    model = Subject       
    template_name = 'subjects/subject_details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class AddSubject(CreateView):
    model = Subject
    form_class = SubjectForm
    template_name = 'subjects/subject_add.html'
    success_url = reverse_lazy('subject-list')
    

#VIEW
def home(request):
    return render(request, 'home.html')


@login_required
def students_list(request):

    # Calling the MODEL and asking for data
    students = Student.objects.all().order_by('last_name')
    pets = Pet.objects.all()

    context = {
        "students": students,
        "pets": pets,
    }

    # Calling the TEMPLATE and asking for an html page to be built
    html = render(request, 'students.html', context)

    return html


def add_student(request):


    if request.method == 'GET':
        form = AddStudentForm()
        return render(request, 'add_student.html', {'form' : form})


    if request.method == 'POST':
        form = AddStudentForm(request.POST)

        if form.is_valid():

            profile = Profile.objects.create(
                major=form.cleaned_data['major'], 
                minor=form.cleaned_data['minor'], 
                picture=form.cleaned_data['picture'], 
            )

            Student.objects.create(
                first_name = form.cleaned_data['first_name'],
                last_name = form.cleaned_data['last_name'],
                profile = profile
            )

            return redirect('students')
        
        else:
            return render(request, 'add_student.html', {'form' : form})
        


def student_details(request, id):
    # student = Student.objects.get(id=id)
    student = get_object_or_404(Student, id=id)

    return render(request, 'student-details.html', {"student": student})   
    

def search(request):
    colors = [ "green", "pink", "cyan", "orange", "purple"]
    
    sleep(3)
    
    data = json.loads(request.body)
   
    result = Student.objects.filter(first_name__icontains=data['searchterm'])
    
    students = []
    for student in result:
        students.append(f"{student.first_name} {student.last_name}")
    
    print(students)

    response = json.dumps({'info':students, 'color':choice(colors)})

    return HttpResponse(response)

WEEK 9/Day 4/school_proj/students/templates/add_student.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load static %}


{% block content %}

    {% include 'navbar.html' %}
    <div class="container-fluid">
        <br>
        <h2>Add a student</h2>
        <form method="POST" class="mt-4">
            <div class="row">
                <div class="col col-4">
                    {% csrf_token %}
                    {{form|bootstrap}}
                    <input class="btn btn-primary" type="submit">
                </div>
            </div>
        </form>
    </div>

    {% block js %}
        <script src="{% static 'js/script.js'%}"></script>
    {% endblock %}

{% endblock %}

WEEK 9/Day 4/school_proj/students/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> 
    <link rel="stylesheet" href="{% static 'css/style.css' %}">   
</head>
<body>
    {% block content %}
    <h1>This is from base</h1>
    {% endblock %}

    {% block js %}
    {% endblock %}
</body>
</html>

WEEK 9/Day 4/school_proj/students/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {{ block.super }}

    {% include 'navbar.html' %}
    <div class="container-fluid">
        <h1>Welcome Home 
            {% if not request.user.is_anonymous %}
                {{request.user.first_name}}
            {% else %}
                Stranger
            {% endif %}!</h1>

        <h1>{{message}}</h1>
        <h3>See our students</h3>
        <a href="{% url 'students' %}">Students Page</a>

        <h3>Add a Subject</h3>
        <a href="{% url 'subject-add' %}">Add Subject</a>            

        <hr>

        <h1>Search</h1>
        <input id="search-input" type="text">
        <button id="search-button">Search</button>
        <div id="search-results"></div>
    </div>

    <script>    


        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }


        const sbutton = document.getElementById('search-button');
        const sinput = document.getElementById('search-input');
        const sresults = document.getElementById('search-results');
        const csrftoken = getCookie('csrftoken');

        
        sbutton.addEventListener('click', function(){

            sresults.style.backgroundColor = "red"

            fetch("{% url 'search' %}", {
                method: 'POST',
                headers: {"X-CSRFToken": csrftoken, 'Content-Type': 'application/json'},
                body: JSON.stringify({"searchterm": sinput.value}),
            })
            .then(resp => resp.json())
            .then(result => {
                sresults.innerHTML = ""
                data = result['info']
                sresults.innerText = "Results"
                for (student of data){
                    item = document.createElement('p');
                    item.innerText = student
                    sresults.appendChild(item)
                    sresults.style.backgroundColor = result['color']
                }
            })
            sresults.style.backgroundColor = "blue"
            sresults.innerText = "Searching..."
        })
    </script>
{% endblock %}

WEEK 9/Day 4/school_proj/students/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

WEEK 9/Day 4/school_proj/students/templates/student-details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {{ block.super }}

    {% include 'navbar.html' %}
    <div class="container-fluid">
        <h1>{{student.first_name}} {{student.last_name}}</h1>
        <h3>Subjects</h3>
        <p>{{student.profile.major}}</p>
        <p>{{student.profile.minor}}</p>
        <img src="{{student.profile.picture}}" alt="" width=100 height=100>
        <h3>Pets</h3>
        {% for pet in student.pet_set.all %}
        <p>{{pet}}</p>
        {% endfor %}
    <br>
    <a class="btn btn-secondary" href="{% url 'students' %}">Back</a>
    </div>
{% endblock %}

WEEK 9/Day 4/school_proj/students/templates/students.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {{ block.super }}

    {% include 'navbar.html' %}
    <div class="container-fluid">
        
        <h1>Welcome To the Students Page!</h1>
        
        <img src="{% static 'images/giraffe.png' %}" width=200 height=200 alt="">

        <h1>Student List</h1>
        <a href="{% url 'students-add' %}">Add a student</a>
        <div id="wrapper">
            {% for student in students %}
            <div id="student-wrapper">
                <a href="{% url 'students-details' id=student.id %}"><h3 class="text-success">{{student.first_name}} {{student.last_name}}</h3></a>
            </div>
            {% endfor %}
            <hr>
        </div>
            <h1>Pets List</h1>
            {% for pets in pets %}
                <p>{{pets.name}} - {{pets.breed}},  Owned By: {{pets.owner}}</p>
            {% endfor %}
    </div>
{% endblock %}

WEEK 9/Day 4/school_proj/students/templates/subjects/subject_add.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load static %}


{% block content %}

    {% include 'navbar.html' %}
    <div class="container-fluid">
        <br>
        <h2>Add a subject</h2>
        <form method="POST" class="mt-4">
            <div class="row">
                <div class="col col-4">
                    {% csrf_token %}
                    {{form|bootstrap}}
                    <input class="btn btn-primary" type="submit">
                </div>
            </div>
        </form>
    </div>

{% endblock %}

WEEK 9/Day 4/school_proj/students/templates/subjects/subject_details.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load static %}


{% block content %}

    {% include 'navbar.html' %}
    <div class="container-fluid">
        <br>
        <h1>{{heading}}</h1>
        <h2>{{subject.name}}</h2>
        <p>Textbook: {{subject.textbook}}</p>
        <p>Class: {{subject.class_room}}</p>
        <hr>
        <a class="btn btn-secondary" href="{% url 'subject-list' %}">Back</a>
    </div>

{% endblock %}

WEEK 9/Day 4/school_proj/students/templates/subjects/subject_list.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load static %}


{% block content %}

    {% include 'navbar.html' %}
    <div class="container-fluid">
        <br>
        <h2>Subjects</h2>
        {% for subject in subject_list %}
            <a href="{% url 'subject-details' subject.id %}"><h3>{{subject.name}}</h3></a>        
        {% endfor%}
        <hr>
        <a class="btn btn-primary" href="{% url 'subject-add' %}">Add Subject</a>
    </div>

{% endblock %}